// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewsPaperAPI.Models;

public partial class Article
{
    [Key]
    public int Id { get; set; }

    public string Title { get; set; }

    public byte[] Image { get; set; }

    public string Info { get; set; }

    public bool? IsDeleted { get; set; }

    public int? UserId { get; set; }
}